"""
Django settings for pandorabox project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xt@$(g)z_v!+_pcvl$z*u$b2r0j8trq6f_c(y*4_c*n^^_q3-+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['*']

# Application definition


INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'swampdragon',
    'import_export',
    'ceamon',
    'main',
    'overview',
    'locker',
    'systemlist',
    'todo',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',

)

ROOT_URLCONF = 'pandorabox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates', 'static'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.core.context_processors.static',
                'ws4redis.context_processors.default',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pandorabox.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# settings.py
DATABASES = {
        'default': {
                # El tipo de bbdd que usamos
        'ENGINE': 'django.db.backends.mysql',
        # Nombre de BBDD
        'NAME': 'ceamon',
        # Nuestro usuario y password
        'USER': 'admin',
        'PASSWORD': 'admin',
        # Localizacion y puerto, en nuestro caso lo dejamos por defecto:
        'HOST': '',
        # Puerto
        'PORT': '',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

#STATIC_ROOT = 'static/'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
os.path.join(BASE_DIR, 'static')
)


LOGIN_REDIRECT_URL = '/'

# Rest:
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
    #'rest_framework.permissions.AllowAny',
    #'rest_framework.authentication.BasicAuthentication',
    #'rest_framework.authentication.SessionAuthentication',
    #'rest_framework.permissions.IsAdminUser',
    'rest_framework.permissions.IsAuthenticated',

    ]
}

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

TEMPLATE_DIRS = [
    os.path.join(BASE_DIR, 'templates')
]

TEMPLATE_CONTEXT_PROCESSORS = (
    'pandorabox.context_processors.dragon_url',
)

# SwampDragon settings
SWAMP_DRAGON_CONNECTION = ('swampdragon.connections.sockjs_connection.DjangoSubscriberConnection', '/data')
TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

SWAMP_DRAGON_HOST = 'localhost' # default '127.0.0.1'
SWAMP_DRAGON_PORT = '9999' # default '9999'
DRAGON_URL = 'http://localhost:9999' # default 'http://localhost:9999'

SWAMP_DRAGON_HEARTBEAT_ENABLED = True
SWAMP_DRAGON_HEARTBEAT_FREQUENCY = 1000 * 60 * 5  # Five minutes


